# -*- coding: utf-8 -*-
"""Resume classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12n_0fxjvIRrPJtGgLL5RI50v8TLJX6FL
"""

pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import pickle
import joblib
model = joblib.load("/content/modelDT.pkl")
model = joblib.load("/content/vector.pkl")

# Streamlit app
st.title("Resume Classification App")
st.write("Upload a resume or type text to classify it into predefined categories.")

# Sidebar for training the model
if st.sidebar.button("Train Model"):
    train_model()

# Resume upload or text input
resume_input = st.text_area("Paste Resume Text Here")

if st.button("Classify Resume"):
    if resume_input.strip():
        category = classify_resume(resume_input)
        st.success(f"The resume is classified as: {category}")
    else:
        st.warning("Please provide resume text to classify.")

